JMS Workshop1 FY2023 Q1 Updates
tchoo-oracle/jms-livelabs-staging-developer pull request #1
Opened 2022-06-27 10:41 UTC by ESoapW

[Reference](https://confluence.oci.oraclecorp.com/display/AJ/FY2023+Quarterly+Review+and+Enhancements)

2022-06-27 16:37 UTC, tchoo-oracle commented on java-management/set-up-of-management-agent-linux/set-up-of-management-agent-linux.md
> +8. JMS has been linked to the management agent and will collect information on your Java runtimes. The scanning frequency was set in [Lab 2: Set Up a Fleet](?lab=setup-a-fleet).
JMS has been linked to the management agent and will collect information on your Java runtimes based on the scanning frequency defined in Lab 2

2022-06-27 16:40 UTC, tchoo-oracle commented on java-management/set-up-of-management-agent-windows/set-up-of-management-agent-windows.md
> +8. JMS has been linked to the management agent and will collect information on your Java runtimes. The scanning frequency was set in [Lab 2: Set Up a Fleet](?lab=setup-a-fleet).
same comment as above

2022-06-27 16:46 UTC, tchoo-oracle requested changes
pls resolve feedback and update PR

2022-06-28 00:23 UTC, enhl-orc commented on java-management/deploy-a-java-application/deploy-a-java-application.md
> +  Please use a new instance with AMD or Intel shape.
Please use a new instance with AMD or Intel shape instead of Ampere.

2022-06-28 00:27 UTC, enhl-orc requested changes
Left minor comments.

2022-06-28 02:50 UTC, tchoo-oracle approved these changes

2022-06-28 03:41 UTC, enhl-orc approved these changes

2022-06-28 03:42 UTC, merged