Updated to 6.0 release
tchoo-oracle/jms-livelabs-staging-developer pull request #14
Opened 2022-11-28 01:08 UTC by somik-oracle

- Added new Labs
- Updated existing Labs
- Updated screenshots

# WMS ID 3202

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

Review link: https://somik-oracle.github.io/jms-livelabs-staging-developer/java-management-lifecycle-management/workshops/tenancy/index.html

2022-11-28 03:41 UTC, sktruong-oracle commented on java-management-lifecycle-management/set-up-and-enable-advanced-features-on-java-management-service/set-up-and-enable-advanced-features-on-java-management-service.md
> +## Task 2: Configure an OCI Managed Instance to enable advanced features
Maybe can make this task and task 3 optional

2022-11-28 03:52 UTC, sktruong-oracle commented on java-management-lifecycle-management/set-up-and-enable-advanced-features-on-java-management-service/set-up-and-enable-advanced-features-on-java-management-service.md
> +> **Note:** Please refer to this task if the **installation script was not used** to install the management agent. The management agent should have been enabled using the Management Agent plugin on y
"This task is only applicable for management agent installed manually, before installation script was available. If you have installed management agent using installation script in [Manage Java Runtimes, Applications and Managed Instances Inventory with Java Management Service](https://apexapps.oracle.com/pls/apex/dbpm/r/livelabs/view-workshop?wid=912), you can skip this task"

2022-11-28 04:01 UTC, sktruong-oracle commented on java-management-lifecycle-management/set-up-and-enable-advanced-features-on-java-management-service/set-up-and-enable-advanced-features-on-java-management-service.md
> +If you are using a non-OCI Managed Instance and it has the Management Agent installed following the steps in the workshop [Manage Java Runtimes, Applications and Managed Instances Inventory with Java
I'd say no need to mention the workshop link here. Since that workshop no longer shows how to install management agent manually. This task is only applicable for manually installed agents

2022-11-28 07:55 UTC, sktruong-oracle requested changes

2022-11-28 07:55 UTC, sktruong-oracle commented on java-management-lifecycle-management/detect-java-libraries/detect-java-libraries.md
> +	3. When the Java library is not found in the NVD, **N/A** will be indicated in the **Version** column and **No matches** found will be shown under the **CVSS score** column.
I think there's some confusion here. N/A version appears when agent is unable to detect a library version or version is not there and the agent report back to jms backend as "n/a". CVSS score column showing No Match Found when we're unable to match a library with a recond in NVD.

2022-11-28 07:55 UTC, sktruong-oracle commented on java-management-lifecycle-management/detect-java-libraries/detect-java-libraries.md
> +	3. When the Java library is not found in the NVD, **N/A** will be indicated in the **Version** column and **No matches** found will be shown under the **CVSS score** column.
**No matches found** instead of **No matches** found

2022-11-28 07:55 UTC, sktruong-oracle commented on java-management-lifecycle-management/detect-java-libraries/detect-java-libraries.md
> +	3. When the Java library is not found in the NVD, **N/A** will be indicated in the **Version** column and **No matches** found will be shown under the **CVSS score** column.
need to update the screenshot as well. It's showing "0" instead of "No matches found"

2022-12-08 08:12 UTC, enhl-orc approved these changes
Checking if directory name change will be alright, otherwise, looks good.

2022-12-09 03:37 UTC, tchoo-oracle approved these changes

2022-12-09 03:40 UTC, merged